(async function () {
  "use strict";
  if (!await window.PsyHealthStorage.adminSession()) { location.replace("admin-login.html"); return; }
  const app=document.getElementById("historyDetailApp"), id=new URLSearchParams(location.search).get("id");
  const esc=value=>String(value??"").replace(/[&<>"']/gu,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const formatTopics=topics=>(topics||[]).map(topic=>topic==="婚恋"+"难题"?"婚恋情感":topic).join("、");
  app.innerHTML='<section class="panel"><p class="loading-state">正在读取云端详细结果…</p></section>';
  let record; try { record=await window.PsyHealthStorage.getRecord(id); } catch(error) { app.innerHTML=`<section class="panel"><p class="error-text">${esc(error.message)}</p></section>`; return; }
  const names={"legacy-psy90":"心理健康90自测量表","legacy-personality85":"人格85自测量表","legacy-love40":"爱情关系合适度测评","common-psq":"父母问卷（PSQ）","common-interpersonal":"人际关系综合诊断量表","common-sds":"抑郁自评量表（SDS）","common-enrich":"婚姻质量问卷","common-wellbeing":"幸福感指数量表","common-sas":"焦虑自评量表（SAS）","common-ucla":"孤独感自评量表（UCLA）"};
  if(!record){app.innerHTML='<section class="panel"><h1>记录不存在</h1><a href="history.html">返回历史列表</a></section>';return;}
  const i=record.intake||{}, results=record.results||[];
  const facts=`<dl class="report-facts"><div class="wide"><dt>所属机构</dt><dd>${esc(record.organizationName || "系统直属")} · ${esc(record.institutionCode || "-")}</dd></div><div><dt>姓名</dt><dd>${esc(i.name)}</dd></div><div><dt>手机号后四位</dt><dd>${esc(i.phoneLast4 || "-")}</dd></div><div><dt>性别</dt><dd>${esc(i.gender)}</dd></div><div><dt>出生年</dt><dd>${esc(i.birthYear || "-")}${i.birthYear ? " 年" : ""}</dd></div><div><dt>最高学历</dt><dd>${esc(i.education)}</dd></div><div><dt>职业</dt><dd>${esc(i.occupation)}</dd></div><div><dt>婚姻状况</dt><dd>${esc(i.marital)}</dd></div><div><dt>出生城市</dt><dd>${esc(i.birthCity)}</dd></div><div class="wide"><dt>主要咨询议题</dt><dd>${esc(formatTopics(i.topics))}</dd></div></dl>`;
  const items=results.length?results.map((r,n)=>{const details=Array.isArray(r.details)&&r.details.length?r.details:String(r.summary||"").split("；").filter(Boolean);return `<article class="report-result"><div><span class="report-scale">${n+1}. ${esc(names[r.id]||r.shortTitle)}</span><h3>${esc(r.resultTitle)}</h3></div><div class="mini-score"><strong>${esc(r.score)}</strong><span>${esc(r.scoreLabel)}</span></div>${r.summary?`<p class="result-summary">${esc(r.summary)}</p>`:""}<ul class="report-detail-list">${details.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><time class="result-time">完成时间：${new Date(r.completedAt).toLocaleString("zh-CN",{hour12:false})}</time></article>`;}).join(""):'<p class="muted-copy">尚未完成测评。</p>';
  app.innerHTML=`<section class="panel report-panel"><header class="report-header"><p class="eyebrow">来访者详情</p><h1>${esc(i.name)}的测评结果</h1><p>所属机构：${esc(record.organizationName || "系统直属")} · 咨询时间：${new Date(record.createdAt).toLocaleString("zh-CN",{hour12:false})}</p></header><section class="report-block"><h2>来访者信息</h2>${facts}</section><section class="report-block"><h2>每项测评详细结果</h2><p class="report-count">已完成 ${results.length} 项测评</p><div class="report-results">${items}</div></section></section>`;
})();
