(function () {
  "use strict";
  const HISTORY_KEY="psyhealth-participant-history-v1", INTAKE_KEY="psyhealth-session-intake", RESULTS_KEY="psyhealth-session-results", PENDING_KEY="psyhealth-pending-results-v1", ADMIN_KEY="psyhealth-admin-session-v1";
  const config=window.PSYHEALTH_CLOUD_CONFIG;
  function read(key,fallback,storage){try{return JSON.parse(storage.getItem(key)||JSON.stringify(fallback));}catch(_){return fallback;}}
  function localHistory(){return read(HISTORY_KEY,[],localStorage);}
  function writeHistory(records){localStorage.setItem(HISTORY_KEY,JSON.stringify(records));}
  function friendlyError(response,payload){const msg=String(payload?.msg||payload?.message||payload?.error?.message||"");if(response.status===401||response.status===403)return new Error("登录已失效或没有管理权限。");if(msg.includes("Could not find the function")||msg.includes("psyhealth_client_"))return new Error("档案功能尚未完成数据库升级。");if(msg.includes("PhoneNumberOneHourLimit"))return new Error("这个手机号 1 小时内接收验证码次数已达上限，请稍后再试或换一个手机号。");if(msg.includes("PhoneNumberDailyLimit"))return new Error("这个手机号今天接收验证码次数已达上限，请明天再试或换一个手机号。");if(msg.includes("LimitExceeded"))return new Error("短信发送过于频繁，请稍后再试或换一个手机号。");if(msg.includes("Anonymous sign-ins are disabled"))return new Error("手机号注册尚未在云端开启，请联系管理员检查认证设置。");if(msg.includes("Unexpected status code returned from hook")||msg.includes("hook")||msg.toLowerCase().includes("sms"))return new Error("验证码暂时发送失败，可能是该手机号请求过于频繁。请稍后再试；如果已经收到验证码，可以直接输入继续。");if(msg.includes("Signup requires a valid password")||msg.includes("valid password"))return new Error("请先设置至少 8 位密码，再发送验证码。");if(msg.includes("New password should be different"))return new Error("新密码与当前密码相同。");if(msg.includes("User already registered")||msg.includes("already registered"))return new Error("这个手机号已经注册过，请直接登录或使用找回密码。");if(msg.includes("Invalid login credentials"))return new Error("账号或密码不正确，请核对后重试。");if(msg.includes("For security purposes")||msg.includes("rate limit"))return new Error("发送过于频繁，请稍后再试。");if(msg.includes("organization_name_exists"))return new Error("机构名称已存在，请换一个注册名。");if(msg.includes("organization_name_required"))return new Error("请先填写机构名称。");if(msg.includes("client_name_required"))return new Error("请填写姓名。姓名将作为下次进入档案的凭证。");if(msg.includes("phone_last4_required"))return new Error("请填写手机号后四位，用于下次快速找回资料。");if(msg.includes("client_name_exists")){const suggested=msg.split("client_name_exists:")[1]||"";return new Error(`该姓名已存在，但手机号后四位不一致。如不是本人，请使用推荐姓名${suggested?`：${suggested}`:""}。`);}if(msg.includes("organization_not_found"))return new Error("没有找到这个机构名称，请核对后重试。");if(msg.includes("invalid_invite"))return new Error("机构代码无效或已停用，请核对后重试。");if(msg.includes("organization_code_limit"))return new Error("每个机构最多只能设置 3 组机构代码。");if(msg.includes("organization_inactive"))return new Error("机构账号已暂停、到期或尚未开通。");if(msg.includes("work_log_required"))return new Error("请先填写工作日志内容。");if(payload?.code==="23505")return new Error("该名称已存在。如不是本人档案，请更换一个便于识别的姓名。");return new Error(msg&&/[A-Za-z]/.test(msg)?"操作失败，请稍后重试。":msg||"云端连接失败，请稍后重试。");}
  async function request(url,options={}){if(!config?.url||!config?.publishableKey)throw new Error("云数据库尚未配置。");const response=await fetch(url,options);const text=await response.text();let payload=null;try{payload=text?JSON.parse(text):null;}catch(_){payload=text;}if(!response.ok)throw friendlyError(response,payload);return payload;}
  async function authRequest(path,body,token,method="POST"){return request(`${config.url}/auth/v1/${path}`,{method,headers:{apikey:config.publishableKey,Authorization:`Bearer ${token||config.publishableKey}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});}
  function normalizePhone(value){let phone=String(value||"").trim().replace(/[\s-]/g,"");if(!phone)return phone;if(phone.startsWith("+"))return phone;if(/^86\d{11}$/.test(phone))return `+${phone}`;if(/^1\d{10}$/.test(phone))return `+86${phone}`;return phone;}
  function validPhone(value){const phone=normalizePhone(value);if(!/^\+861\d{10}$/.test(phone))throw new Error("请输入正确的手机号。");return phone;}
  function saveAdminSession(payload){if(!payload?.access_token||!payload?.refresh_token)throw new Error("验证码已通过，但云端没有返回登录状态，请稍后重试。");const session={accessToken:payload.access_token,refreshToken:payload.refresh_token,expiresAt:Date.now()+(payload.expires_in||3600)*1000,email:payload.user?.email||"",phone:payload.user?.phone||""};sessionStorage.setItem(ADMIN_KEY,JSON.stringify(session));return session;}
  async function adminSession(){let session=read(ADMIN_KEY,null,sessionStorage);if(!session)return null;if(session.expiresAt>Date.now()+60000)return session;try{return saveAdminSession(await authRequest("token?grant_type=refresh_token",{refresh_token:session.refreshToken}));}catch(_){sessionStorage.removeItem(ADMIN_KEY);return null;}}
  async function adminSignIn(identifier,password){const account=String(identifier).trim();let body;if(account.includes("@"))body={email:account,password};else if(/^(\+?86)?1\d{10}$/.test(account.replace(/[\s-]/g,"")))body={phone:validPhone(account),password};else{const found=await rpc("psyhealth_login_phone_by_name",{p_name:account});body={phone:found.phone,password};}return saveAdminSession(await authRequest("token?grant_type=password",body));}
  async function checkOrgName(name){return rpc("psyhealth_check_org_name",{p_name:name});}
  async function signUp(phone,password,name){await checkOrgName(name);return authRequest("otp",{phone:validPhone(phone),data:{organization_name:name},create_user:true});}
  async function verifyPhone(phone,token){return saveAdminSession(await authRequest("verify",{phone:validPhone(phone),token,type:"sms"}));}
  async function resendSignup(phone){return authRequest("otp",{phone:validPhone(phone),create_user:false});}
  async function requestPasswordReset(phone){return authRequest("otp",{phone:validPhone(phone),create_user:false});}
  async function verifyRecovery(phone,token){return saveAdminSession(await authRequest("verify",{phone:validPhone(phone),token,type:"sms"}));}
  async function adminSignOut(){const session=await adminSession();try{if(session)await authRequest("logout",null,session.accessToken);}finally{sessionStorage.removeItem(ADMIN_KEY);}}
  async function adminChangePassword(password){const session=await adminSession();if(!session)throw new Error("请重新登录。");await authRequest("user",{password},session.accessToken,"PUT");}
  async function rpc(name,body={},needsAdmin=false){const session=needsAdmin?await adminSession():null;if(needsAdmin&&!session)throw new Error("请先登录管理员账户。");return request(`${config.url}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:config.publishableKey,"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.accessToken}`}:{})},body:JSON.stringify(body)});}

  async function validateInvite(code){return rpc("psyhealth_validate_invite",{p_code:code});}
  async function lookupClientProfile(name,phoneLast4,code){return rpc("psyhealth_client_lookup",{p_name:name,p_phone_last4:phoneLast4,p_code:code||null});}
  async function begin(intake,code){const completedAt=new Date().toISOString();let cloud;try{cloud=await rpc("psyhealth_client_begin",{p_intake:{...intake,completedAt},p_code:code});}catch(error){if(!String(error.message).includes("数据库升级"))throw error;cloud=await rpc("psyhealth_begin_participant",{p_intake:{...intake,completedAt},p_code:code});}const profile=cloud.intake||intake;const saved={...profile,recordId:cloud.id,clientId:cloud.clientId,editToken:cloud.editToken,allowedScales:cloud.allowedScales,organizationName:cloud.organizationName,completedAt:cloud.createdAt||completedAt,isExisting:cloud.isExisting};sessionStorage.setItem(INTAKE_KEY,JSON.stringify(saved));sessionStorage.setItem(RESULTS_KEY,"[]");const records=localHistory();records.push({id:saved.recordId,clientId:saved.clientId,intake:saved,results:[],createdAt:saved.completedAt,updatedAt:saved.completedAt});writeHistory(records);return saved;}
  function saveLocalResult(record){let results=read(RESULTS_KEY,[],sessionStorage);results.push(record);sessionStorage.setItem(RESULTS_KEY,JSON.stringify(results));const intake=read(INTAKE_KEY,null,sessionStorage),records=localHistory(),index=records.findIndex(item=>item.id===intake?.recordId);if(index>=0){records[index]={...records[index],intake,results,updatedAt:new Date().toISOString()};writeHistory(records);}return intake;}
  async function pushResult(intake,record){const saved=await rpc("psyhealth_save_result",{p_id:intake.recordId,p_edit_token:intake.editToken,p_result:record});if(!saved)throw new Error("云端记录凭证已失效。");}
  async function saveResult(record){const intake=saveLocalResult(record);if(!intake?.recordId||!intake?.editToken)return;try{await pushResult(intake,record);}catch(error){const pending=read(PENDING_KEY,[],localStorage).filter(item=>!(item.recordId===intake.recordId&&item.result.id===record.id));pending.push({recordId:intake.recordId,editToken:intake.editToken,result:record});localStorage.setItem(PENDING_KEY,JSON.stringify(pending));window.dispatchEvent(new CustomEvent("psyhealth-cloud-sync-error",{detail:error.message}));}}
  async function syncPending(){const pending=read(PENDING_KEY,[],localStorage),remaining=[];for(const item of pending){try{await pushResult({recordId:item.recordId,editToken:item.editToken},item.result);}catch(_){remaining.push(item);}}localStorage.setItem(PENDING_KEY,JSON.stringify(remaining));}
  async function history(){return rpc("psyhealth_admin_list",{},true);}
  async function getRecord(id){return rpc("psyhealth_admin_get",{p_id:id},true);}
  async function deleteRecords(ids){await rpc("psyhealth_admin_delete",{p_ids:ids},true);const selected=new Set(ids);writeHistory(localHistory().filter(item=>!selected.has(item.id)));}
  async function saveClientMessage(id,token,message){return rpc("psyhealth_client_save_message",{p_id:id,p_edit_token:token,p_message:message});}
  async function clientProfiles(){return rpc("psyhealth_client_profiles",{},true);}
  async function clientProfile(id){return rpc("psyhealth_client_profile",{p_client_id:id},true);}
  async function saveWorkLog(clientId,logId,content){return rpc("psyhealth_client_save_work_log",{p_client_id:clientId,p_log_id:logId||null,p_content:content},true);}
  async function deleteWorkLog(logId){return rpc("psyhealth_client_delete_work_log",{p_log_id:logId},true);}
  async function adminInvites(){return rpc("psyhealth_admin_invites",{},true);}
  async function saveInvite(invite){return rpc("psyhealth_admin_save_invite",{p_id:invite.id||null,p_code:invite.code,p_label:invite.label,p_allowed_scales:invite.allowedScales,p_active:invite.active},true);}
  async function deleteInvite(id){return rpc("psyhealth_admin_delete_invite",{p_id:id},true);}
  async function myRole(){return rpc("psyhealth_my_role",{},true);}
  async function ensureOrganization(name){return rpc("psyhealth_ensure_organization",{p_name:name||"未命名机构"},true);}
  async function orgCodes(){return rpc("psyhealth_org_codes",{},true);}
  async function saveOrgCode(item){return rpc("psyhealth_org_save_code",{p_id:item.id||null,p_label:item.label,p_allowed_scales:item.allowedScales,p_active:item.active},true);}
  async function deleteOrgCode(id){return rpc("psyhealth_org_delete_code",{p_id:id},true);}
  async function organizations(){return rpc("psyhealth_system_organizations",{},true);}
  async function updateOrganization(userId,status,months){return rpc("psyhealth_system_update_organization",{p_user_id:userId,p_status:status,p_add_months:months},true);}
  async function setOrganizationExpiry(userId,expiresOn){return rpc("psyhealth_system_set_organization_expiry",{p_user_id:userId,p_expires_on:expiresOn},true);}
  async function setOrganizationNote(userId,note){return rpc("psyhealth_system_set_org_note",{p_user_id:userId,p_note:note},true);}
  async function renameOrganization(name){return rpc("psyhealth_org_rename",{p_name:name},true);}
  async function deleteOrganization(userId){return rpc("psyhealth_system_delete_organization",{p_user_id:userId},true);}
  window.addEventListener("online",syncPending);syncPending().catch(()=>{});
  window.PsyHealthStorage={validateInvite,lookupClientProfile,begin,saveResult,saveClientMessage,history,getRecord,deleteRecords,clientProfiles,clientProfile,saveWorkLog,deleteWorkLog,adminInvites,saveInvite,deleteInvite,adminSignIn,adminSignOut,adminChangePassword,adminSession,signUp,verifyPhone,resendSignup,requestPasswordReset,verifyRecovery,myRole,ensureOrganization,orgCodes,saveOrgCode,deleteOrgCode,organizations,updateOrganization,setOrganizationExpiry,setOrganizationNote,renameOrganization,deleteOrganization,readSessionIntake:()=>read(INTAKE_KEY,null,sessionStorage)};
})();
